Allow passing options to websocket_client
Aircloak/phoenix_gen_socket_client pull request #52
Opened 2020-10-19 17:25 UTC by albertored

`:websocket_client` supports these options:

> %% Supported Opts:
%%  - {keepalive, integer()}:  keepalive timeout in ms
%%  - {extra_headers, list({K, V})}: a kv-list of headers to send in the handshake
%% (useful if you need to add an e.g. 'Origin' header on connection.
%%  - {ssl_verify, verify_none | verify_peer | {verify_fun, _}} : this is passed
%%  through to ssl:connect/2,3.

This PR allows to set only the `:extra_headers` and `:ssl_verify` one (I need `:extra_headers` for adding an `Authorization` header to the connect request). I haven't added also the `:keepalive` one because I think is already handled in other ways but if you think it's useful we can add it too.

2020-10-22 14:39 UTC, edongashi requested changes
Hi @albertored, thank you for submitting this change!

Could you please also update the module doc at `web_socket_client.ex` to mention these added flags?
You can simply mention that these two options will be forwarded to the underlying library.

2020-10-22 18:43 UTC, albertored commented
Sure, I will push the changes tomorrow

2020-10-23 15:09 UTC, edongashi approved these changes
Thanks!

2020-10-23 15:10 UTC, edongashi commented
We will make a minor release with your changes soon.

2020-10-26 08:48 UTC, merged

2020-10-26 10:19 UTC, sebastian commented
[3.2.0 release has been made](https://hex.pm/packages/phoenix_gen_socket_client/3.2.0)